platform :ios, '7.0'
pod 'GoogleMaps', '~> 1.10.5'
pod 'AFNetworking', '~> 1.3.2'
pod 'MBProgressHUD'
pod 'RSKImageCropper', '~> 1.4'
pod 'MBCircularProgressBar'
pod 'ColorArt', '~> 0.1'
pod 'EBPhotoPages', '~> 0.9'
pod 'Parse'